apps/consorcios/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

from . import views

app_name = "consorcios_app"

urlpatterns = [
    path(
        'accounts/login/',
        views.LoginView.as_view(),
        name='login',
    ),
    path(
        'logout',
        views.LogoutView.as_view(),
        name='logout',
    ),
    path(
        'crear-reporte/consorcios',
        login_required(views.Consorcios.as_view()),
        name='consorcios-list',
    ),
    path(
        'crear-reporte/<slug:slug>',
        login_required(views.Sectores.as_view()),
        name='sectores-list',
    ),
]

apps/reportes/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

from . import views

app_name = "reportes_app"

urlpatterns = [
    path(
        'crear-reporte/<slug:slug>/crear',
        login_required(views.ReporteView.as_view()),
        name='reporte-add',
    ),
    path(
        'crear-reporte/<slug:slug>/unidad',
        login_required(views.ReporteUnidadView.as_view()),
        name='reporte-unidad-add',
    ),
    path(
        'crear-reporte/<slug:slug>/obra',
        login_required(views.ReporteObraView.as_view()),
        name='reporte-obra-add',
    ),
    path(
        'reportes/consorcios',
        views.ConsorciosReportes.as_view(),
        name='reportes-consorcios-list',
    ),
    path(
        'reportes/<slug:slug>/',
        views.ReportesList.as_view(),
        name='reportes-list',
    ),
    path(
        'reportes/<str:slug>/<str:date>/',
        views.ReporteSectores.as_view(),
        name='reporte-sectores',
    ),
    path(
        'reportes/<slug:slug>/reporte',
        views.ReporteDetail.as_view(),
        name='reporte',
    ),
    path(
        'reportes/<str:slug>/<str:date>/reporte',
        views.ReporteFull.as_view(),
        name='reporte-full',
    ),
    # path(
    #     'reportes/<str:slug>/<str:date>/',
    #     views.ReporteDetail.as_view(),
    #     name='reporte',
    # ),
]

confiarbr/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.decorators import login_required

from apps.consorcios.views import Home


urlpatterns = [
    path('admin/', admin.site.urls),
    path('chaining/', include('smart_selects.urls')),

    path(
        '',
        Home.as_view(),
        name='home',
    ),
    
    path('', include('apps.consorcios.urls')),
    path('', include('apps.reportes.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/consorcios/models.py
from django.db import models
from django.utils.text import slugify


class Consorcio(models.Model):

    nombre = models.CharField(
        'Consorcio', max_length=255, unique=True
    )
    slug = models.SlugField(
        'Slug', max_length=255, unique=True
    )

    class Meta:

        verbose_name = 'Consorcio'
        verbose_name_plural = 'Consorcios'

    def save(self, *args, **kwargs):
        self.slug = slugify(self.nombre)
        super(Consorcio, self).save(*args, **kwargs)

    def __str__(self):
        return self.nombre


class Sector(models.Model):

    consorcio = models.ForeignKey(
        Consorcio, on_delete=models.CASCADE, verbose_name='consorcio')
    nombre = models.CharField(
        'Sector', max_length=255
    )
    slug = models.SlugField(
        'Slug', max_length=255, blank=True, null=True
    )

    class Meta:

        unique_together = ['consorcio', 'nombre']
        verbose_name = 'Sector'
        verbose_name_plural = 'Sectores'

    def save(self, *args, **kwargs):
        self.slug = slugify(self.consorcio) + '-' + slugify(self.nombre)
        super(Sector, self).save(*args, **kwargs)

    def __str__(self):
        return self.nombre

apps/consorcios/forms.py
from django import forms
from django.contrib.auth import authenticate


class LoginForm(forms.Form):

    username = forms.CharField(
        label='Usuario',
        required=True,
        widget=forms.TextInput(
            attrs={
                'class': 'form-control text-center',
                'placeholder': 'Usuario',
                'autocomplete': 'off',
            }
        ))
    password = forms.CharField(
        label='Contraseña',
        required=True,
        widget=forms.PasswordInput(
            attrs={
                'class': 'form-control text-center',
                'placeholder': 'Contraseña',
                'autocomplete': 'off',
            }
        ))

    def clean(self):
        username = self.cleaned_data['username']
        password = self.cleaned_data['password']

        if not authenticate(username=username, password=password):
            raise forms.ValidationError(
                'Usuario o Contraseña Incorrecta'
            )

        return self.cleaned_data

apps/consorcios/views.py
from django.urls import reverse_lazy
from django.shortcuts import render
from django.views.generic.edit import FormView
from django.views.generic import ListView, DetailView, TemplateView, View
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect
from .models import Consorcio, Sector

from .forms import LoginForm


class Home(TemplateView):
    template_name = "home.html"


class LoginView(FormView):
    template_name = 'login.html'
    form_class = LoginForm
    success_url = reverse_lazy('home')

    def form_valid(self, form):
        user = authenticate(
            username=form.cleaned_data['username'],
            password=form.cleaned_data['password']
        )
        login(self.request, user)
        return super(LoginView, self).form_valid(form)


class Consorcios(ListView):
    model = Consorcio
    template_name = "crear/consorcios.html"

    def get_context_data(self, **kwargs):
        consorcios = super().get_context_data(**kwargs)
        context = {
            'consorcios': consorcios['object_list'],
        }
        return context


class Sectores(DetailView):
    model = Consorcio
    template_name = "crear/sectores.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        consorcio = self.get_object()
        sectores = Sector.objects.filter(consorcio=consorcio.pk)
        context = {
            'consorcio': consorcio,
            'sectores': sectores,
        }
        return context


class LogoutView(View):
    def get(self, request, *args, **kargs):
        logout(request)
        return HttpResponseRedirect(reverse_lazy('consorcios_app:login'))

apps/reportes/views.py
from django.urls import reverse_lazy, reverse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect, JsonResponse, HttpResponse
from django.views.generic.edit import CreateView
from django.views.generic import ListView, DetailView, TemplateView, View

from apps.consorcios.models import Consorcio, Sector
from apps.cuestionario.models import Cuestionario, Pregunta
from .models import Reporte, Respuesta, Unidad, Obras, ImagenRespuesta

from .forms import ReporteForm, RespuestaForm, RespuestaFormSet, UnidadFormSet, ObrasFormSet, ImagenRespuestaFormSet

from datetime import date
from django.utils import timezone

# import os
# from django.conf import settings
# from django.template import Context
# from django.template.loader import get_template
# from xhtml2pdf import pisa


class ReporteView(CreateView):
    model = Reporte
    form_class = ReporteForm
    template_name = "crear/reporte.html"
    success_url = reverse_lazy('home')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        slug_sector = self.kwargs.get('slug')
        sector = Sector.objects.get(slug=slug_sector)
        cuestionario = Cuestionario.objects.get(sector=sector.id)
        preguntas = Pregunta.objects.filter(
            cuestionario=cuestionario.pk,
            estado=True,
            prox_visita__lte=timezone.now()
        ) | Pregunta.objects.filter(
            cuestionario=cuestionario.pk,
            estado=True,
            prox_visita=None
        )
        context['sector'] = sector
        context['preguntas'] = preguntas
        if "respuesta_formset" not in context:
            context['respuesta_formset'] = RespuestaFormSet(
                queryset=Respuesta.objects.none(),
            )
        return context

    def post(self, request, *args, **kwargs):
        self.object = None
        form = self.get_form()
        slug_sector = self.kwargs.get('slug')
        sector = Sector.objects.get(slug=slug_sector)
        respuesta_formset = RespuestaFormSet(request.POST, request.FILES)
        if respuesta_formset.is_valid() and form.is_valid():
            return self.form_valid(form, respuesta_formset, sector)
        else:
            return self.form_invalid(form, respuesta_formset)

    def form_invalid(self, form, respuesta_formset):
        return self.render_to_response(
            self.get_context_data(
                form=form,
                respuesta_formset=respuesta_formset,
            )
        )

    def form_valid(self, form, respuesta_formset, sector):
        reporte = form.save(commit=False)
        reporte.user = self.request.user
        reporte.consorcio = sector.consorcio
        reporte.sector = sector
        reporte.save()
        instancesResp = respuesta_formset.save(commit=False)
        for instanceResp in instancesResp:
            if instanceResp.respuesta != None:
                instanceResp.reporte = reporte
                instanceResp.save()
                pregunta = Pregunta.objects.get(id=instanceResp.pregunta.id)
                pregunta.ultima_visita = date.today()
                pregunta.save()
        # intancesImg = imagen_respuesta_formset.save(commit=False)
        # for instanceImg in intancesImg:
        #     if instanceImg.imagen != None:
        #         instanceImg.save()
        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self):
        sector = Sector.objects.get(slug=self.kwargs.get('slug'))
        return reverse('consorcios_app:sectores-list', kwargs={'slug': sector.consorcio.slug})


class ReporteUnidadView(CreateView):
    model = Reporte
    form_class = ReporteForm
    template_name = "crear/reporte-unidad.html"
    success_url = reverse_lazy('home')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        slug_sector = self.kwargs.get('slug')
        sector = Sector.objects.get(slug=slug_sector)
        context['sector'] = sector
        if "unidad_formset" not in context:
            context['unidad_formset'] = UnidadFormSet(
                queryset=Unidad.objects.none(),
            )
        return context

    def post(self, request, *args, **kwargs):
        self.object = None
        form = self.get_form()
        slug_sector = self.kwargs.get('slug')
        sector = Sector.objects.get(slug=slug_sector)
        unidad_formset = UnidadFormSet(request.POST, request.FILES)
        if unidad_formset.is_valid() and form.is_valid():
            return self.form_valid(form, unidad_formset, sector)
        else:
            return self.form_invalid(form, unidad_formset)

    def form_invalid(self, form, unidad_formset):
        return self.render_to_response(
            self.get_context_data(
                form=form,
                unidad_formset=unidad_formset,
            )
        )

    def form_valid(self, form, unidad_formset, sector):
        if Reporte.objects.filter(
            consorcio=sector.consorcio,
            sector=sector,
            creacion=date.today(),
        ).exists():
            getReporte = Reporte.objects.get(
                consorcio=sector.consorcio,
                sector=sector,
                creacion=date.today(),
            )
            reporte = getReporte
        else:
            reporte = form.save(commit=False)
            reporte.user = self.request.user
            reporte.consorcio = sector.consorcio
            reporte.sector = sector
            reporte.save()
        instancesUnit = unidad_formset.save(commit=False)
        for instanceUnit in instancesUnit:
            if instanceUnit.unidad != None:
                instanceUnit.reporte = reporte
                instanceUnit.save()
        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self):
        sector = Sector.objects.get(slug=self.kwargs.get('slug'))
        return reverse('consorcios_app:sectores-list', kwargs={'slug': sector.consorcio.slug})


class ReporteObraView(CreateView):
    model = Reporte
    form_class = ReporteForm
    template_name = "crear/obras-sectores-comunes.html"
    success_url = reverse_lazy('home')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        slug_sector = self.kwargs.get('slug')
        sector = Sector.objects.get(slug=slug_sector)
        context['sector'] = sector
        if "obras_formset" not in context:
            context['obras_formset'] = ObrasFormSet(
                queryset=Obras.objects.none(),
            )
        return context

    def post(self, request, *args, **kwargs):
        self.object = None
        form = self.get_form()
        slug_sector = self.kwargs.get('slug')
        sector = Sector.objects.get(slug=slug_sector)
        obras_formset = ObrasFormSet(request.POST, request.FILES)
        if obras_formset.is_valid() and form.is_valid():
            return self.form_valid(form, obras_formset, sector)
        else:
            return self.form_invalid(form, obras_formset)

    def form_invalid(self, form, obras_formset):
        return self.render_to_response(
            self.get_context_data(
                form=form,
                obras_formset=obras_formset,
            )
        )

    def form_valid(self, form, obras_formset, sector):
        if Reporte.objects.filter(
            consorcio=sector.consorcio,
            sector=sector,
            creacion=date.today(),
        ).exists():
            getReporte = Reporte.objects.get(
                consorcio=sector.consorcio,
                sector=sector,
                creacion=date.today(),
            )
            reporte = getReporte
        else:
            reporte = form.save(commit=False)
            reporte.user = self.request.user
            reporte.consorcio = sector.consorcio
            reporte.sector = sector
            reporte.save()
        instancesObra = obras_formset.save(commit=False)
        for instanceObra in instancesObra:
            if instanceObra.obra != None:
                instanceObra.reporte = reporte
                instanceObra.save()
        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self):
        sector = Sector.objects.get(slug=self.kwargs.get('slug'))
        return reverse('consorcios_app:sectores-list', kwargs={'slug': sector.consorcio.slug})


class ConsorciosReportes(ListView):
    model = Consorcio
    template_name = "reportes/consorcios.html"

    def get_context_data(self, **kwargs):
        consorcios = super().get_context_data(**kwargs)
        context = {
            'consorcios': consorcios['object_list'],
        }
        return context


class ReportesList(DetailView):
    model = Consorcio
    template_name = "reportes/reporte-list.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        consorcio = self.get_object()
        reportesall = Reporte.objects.filter(
            consorcio=consorcio.pk,
        ).values_list('creacion', flat=True).distinct()
        reportes = Reporte.objects.filter(
            consorcio=consorcio.pk,
        ).values_list('creacion', flat=True).distinct()
        filterY = self.request.GET.get('filterY')
        filterM = self.request.GET.get('filterM')
        if filterY and not filterM:
            reportes = Reporte.objects.filter(
                consorcio=consorcio.pk,
                creacion__year=filterY,
            ).values_list('creacion', flat=True).distinct()
        if filterY and filterM:
            reportes = Reporte.objects.filter(
                consorcio=consorcio.pk,
                creacion__year=filterY,
                creacion__month=filterM
            ).values_list('creacion', flat=True).distinct()
        context = {
            'consorcio': consorcio,
            'reportes': reportes,
            'reportesall': reportesall,
        }
        return context

templates/crear/consorcios.html
{% extends 'layout.html' %}
{% load static %}

{% block title %}Consorcios{% endblock title %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col">
      <h6 class="text-center">Crear Reporte</h6>
      <h1 class="text-center display-6 mb-3">Consorcios</h1>
    </div>
  </div>
  <div class="row">
    <div class="col-10 offset-1 col-sm-8 offset-sm-2 col-md-6 offset-md-3 col-lg-4 offset-lg-4">
      <div class="d-grid gap-2">
        
        {% for c in consorcios %}
        
        <a href="{% url 'consorcios_app:sectores-list' c.slug %}" class="btn btn-outline-primary" type="button">{{ c }}</a>
        
        {% endfor %}
        
      </div>
    </div>
  </div>
  <div class="text-end mt-3">
    <a class="btn btn-primary" href="javascript:history.back()">Atrás</a>
  </div>
</div>
{% endblock content %}

templates/crear/obras-sectores-comunes.html
{% extends 'layout.html' %}
{% load static %}

{% block title %}Cuestionario{% endblock title %}

{% block stylesheet %}
<link rel="stylesheet" href="{% static 'libs/bs-stepper/bs-stepper.min.css' %}">
{% endblock stylesheet %}

{% block css %}
<style>
  .item {
    border: 1px solid var(--bs-primary);
    border-radius: 1rem;
  }
</style>
{% endblock css %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col">
      <h6 class="text-md-center">Crear Reporte</h6>
      <h3 class="text-md-center">Consorcio: {{ sector.consorcio }}</h3>
      <h3 class="text-md-center">{{ sector.nombre }}</h3>
    </div>
  </div>
  <div class="row">
    <div class="col-12 col-sm-8 offset-sm-2 col-md-6 offset-md-3">
      <form enctype="multipart/form-data" method="post">
        {% csrf_token %}

        {{ obras_formset.management_form }}

        <div class="item mt-3 py-3 px-3">
          <div class="mb-3">
            <label for="id_form-0-obra"><strong>Obra en sector común</strong></label>
            <input type="text" name="form-0-obra" id="id_form-0-obra" class="form-control" placeholder="Obra en sector común">
          </div>
          <div class="mb-3">
            <label for="id_form-0-observaciones"><strong>Observaciones</strong></label>
            <textarea name="form-0-observaciones" rows="2" class="form-control" placeholder="Observaciones" style="resize: none;" id="id_form-0-Observaciones"></textarea>
          </div>
          <p class="my-3"><strong>Imagen(es)</strong></p>
          <div class="content-imgfile">
            <input type="file" capture="camera" name="form-0-imagen1" class="imgfile1 form-control" accept="image/*" id="id_form-0-imagen1">
            <input type="file" capture="camera" name="form-0-imagen2" class="imgfile2 form-control d-none" accept="image/*" id="id_form-0-imagen2">
            <input type="file" capture="camera" name="form-0-imagen3" class="imgfile3 form-control d-none" accept="image/*" id="id_form-0-imagen3">
            <input type="file" capture="camera" name="form-0-imagen4" class="imgfile4 form-control d-none" accept="image/*" id="id_form-0-imagen4">
          </div>
          <div class="text-end">
            <a class="btn btn-primary btn-sm mt-3 ms-auto" onclick="addImg(this)">Agregar imagen</a>
          </div>
        </div>

        <div id="btn-guardar" class="d-grid gap-2 mt-3">
          <button class="btn btn-primary disabled" type="submit">Guardar</button>
        </div>
      </form>
    </div>
  </div>
  <div class="text-end mt-3">
    <a class="btn btn-danger" href="javascript:history.back()">Salir</a>
  </div>
</div>
{% endblock content %}

{% block js %}
<script>
  function addImg(elem) {
    var totalImgfile = $(elem).parents().siblings('.content-imgfile').children('input')
    var noImgfile = $(elem).parents().siblings('.content-imgfile').children('input.d-none')
    var nextImgfile = $(totalImgfile).length - $(noImgfile).length + 1
    $(elem).parents().siblings('.content-imgfile').children('input.imgfile'+nextImgfile+'').removeClass('d-none')
    if (nextImgfile == totalImgfile.length) {
      $(elem).addClass('d-none')
    }
  }
  
  $('#id_form-0-obra').change(function() {
    if($('#id_form-0-obra').val() == '') {
      $('#btn-guardar button').addClass('disabled')
    } else {
      $('#btn-guardar button').removeClass('disabled')
    }
  })

</script>
{% endblock js %}

templates/crear/reporte-unidad.html
{% extends 'layout.html' %}
{% load static %}

{% block title %}Cuestionario{% endblock title %}

{% block stylesheet %}
<link rel="stylesheet" href="{% static 'libs/bs-stepper/bs-stepper.min.css' %}">
{% endblock stylesheet %}

{% block css %}
<style>
  .item {
    border: 1px solid var(--bs-primary);
    border-radius: 1rem;
  }
</style>
{% endblock css %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col">
      <h6 class="text-md-center">Crear Reporte</h6>
      <h3 class="text-md-center">Consorcio: {{ sector.consorcio }}</h3>
      <h3 class="text-md-center">{{ sector.nombre }}</h3>
    </div>
  </div>
  <div class="row">
    <div class="col-12 col-sm-8 offset-sm-2 col-md-6 offset-md-3">
      <form enctype="multipart/form-data" method="post">
        {% csrf_token %}

        {{ unidad_formset.management_form }}

        <div class="item mt-3 py-3 px-3">
          <div class="mb-3">
            <label for="id_form-0-unidad"><strong>Unidad</strong></label>
            <input type="text" name="form-0-unidad" id="id_form-0-unidad" class="form-control" placeholder="Unidad">
          </div>
          <div class="mb-3">
            <label for="id_form-0-observaciones"><strong>Observaciones</strong></label>
            <textarea name="form-0-observaciones" rows="2" class="form-control" placeholder="Observaciones" style="resize: none;" id="id_form-0-Observaciones"></textarea>
          </div>
          <p class="my-3"><strong>Imagen(es)</strong></p>
          <div class="content-imgfile">
            <input type="file" capture="camera" name="form-0-imagen1" class="imgfile1 form-control" accept="image/*" id="id_form-0-imagen1">
            <input type="file" capture="camera" name="form-0-imagen2" class="imgfile2 form-control d-none" accept="image/*" id="id_form-0-imagen2">
            <input type="file" capture="camera" name="form-0-imagen3" class="imgfile3 form-control d-none" accept="image/*" id="id_form-0-imagen3">
            <input type="file" capture="camera" name="form-0-imagen4" class="imgfile4 form-control d-none" accept="image/*" id="id_form-0-imagen4">
          </div>
          <div class="text-end">
            <a class="btn btn-primary btn-sm mt-3 ms-auto" onclick="addImg(this)">Agregar imagen</a>
          </div>
        </div>

        <div id="btn-guardar" class="d-grid gap-2 mt-3">
          <button class="btn btn-primary disabled" type="submit">Guardar</button>
        </div>
      </form>
    </div>
  </div>
</div>
{% endblock content %}

{% block js %}
<script>
  function addImg(elem) {
    var totalImgfile = $(elem).parents().siblings('.content-imgfile').children('input')
    var noImgfile = $(elem).parents().siblings('.content-imgfile').children('input.d-none')
    var nextImgfile = $(totalImgfile).length - $(noImgfile).length + 1
    $(elem).parents().siblings('.content-imgfile').children('input.imgfile'+nextImgfile+'').removeClass('d-none')
    if (nextImgfile == totalImgfile.length) {
      $(elem).addClass('d-none')
    }
  }
  
  $('#id_form-0-unidad').change(function() {
    if($('#id_form-0-unidad').val() == '') {
      $('#btn-guardar button').addClass('disabled')
    } else {
      $('#btn-guardar button').removeClass('disabled')
    }
  })

</script>
{% endblock js %}

templates/crear/sectores.html
{% extends 'layout.html' %}
{% load static %}

{% block title %}{{ consorcio.nombre }}{% endblock title %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col">
      <h6 class="text-center">Crear Reporte</h6>
      <h1 class="text-center display-6 mb-3">{{ consorcio.nombre }}</h1>
    </div>
  </div>
  <div class="row">
    <div class="col-10 offset-1 col-sm-8 offset-sm-2 col-md-6 offset-md-3 col-lg-4 offset-lg-4">
      <div class="d-grid gap-2">
        
        {% for s in sectores %}
        
        {% if s.nombre == 'Unidades' %}
        <a href="{% url 'reportes_app:reporte-unidad-add' s.slug %}" class="btn btn-outline-primary" type="button">Unidades</a>
        {% elif s.nombre == 'Obras en sectores comunes' %}
        <a href="{% url 'reportes_app:reporte-obra-add' s.slug %}" class="btn btn-outline-primary" type="button">Obra en sector común</a>
        {% else %}
        <a href="{% url 'reportes_app:reporte-add' s.slug %}" class="btn btn-outline-primary" type="button">{{ s }}</a>
        {% endif %}
        
        {% endfor %}
        
      </div>
    </div>
  </div>
  <div class="text-end mt-3">
    <a class="btn btn-primary" href="javascript:history.back()">Atrás</a>
  </div>
</div>
{% endblock content %}