apps/consorcios/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

from . import views

app_name = "consorcios_app"

urlpatterns = [
    path(
        'accounts/login/',
        views.LoginView.as_view(),
        name='login',
    ),
    path(
        'logout',
        views.LogoutView.as_view(),
        name='logout',
    ),
    path(
        'crear-reporte/consorcios',
        login_required(views.Consorcios.as_view()),
        name='consorcios-list',
    ),
    path(
        'crear-reporte/<slug:slug>',
        login_required(views.Sectores.as_view()),
        name='sectores-list',
    ),
]

apps/reportes/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

from . import views

app_name = "reportes_app"

urlpatterns = [
    path(
        'crear-reporte/<slug:slug>/crear',
        login_required(views.ReporteView.as_view()),
        name='reporte-add',
    ),
    path(
        'crear-reporte/<slug:slug>/unidad',
        login_required(views.ReporteUnidadView.as_view()),
        name='reporte-unidad-add',
    ),
    path(
        'crear-reporte/<slug:slug>/obra',
        login_required(views.ReporteObraView.as_view()),
        name='reporte-obra-add',
    ),
    path(
        'reportes/consorcios',
        views.ConsorciosReportes.as_view(),
        name='reportes-consorcios-list',
    ),
    path(
        'reportes/<slug:slug>/',
        views.ReportesList.as_view(),
        name='reportes-list',
    ),
    path(
        'reportes/<str:slug>/<str:date>/',
        views.ReporteSectores.as_view(),
        name='reporte-sectores',
    ),
    path(
        'reportes/<slug:slug>/reporte',
        views.ReporteDetail.as_view(),
        name='reporte',
    ),
    path(
        'reportes/<str:slug>/<str:date>/reporte',
        views.ReporteFull.as_view(),
        name='reporte-full',
    ),
    # path(
    #     'reportes/<str:slug>/<str:date>/',
    #     views.ReporteDetail.as_view(),
    #     name='reporte',
    # ),
]

confiarbr/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.decorators import login_required

from apps.consorcios.views import Home


urlpatterns = [
    path('admin/', admin.site.urls),
    path('chaining/', include('smart_selects.urls')),

    path(
        '',
        Home.as_view(),
        name='home',
    ),
    
    path('', include('apps.consorcios.urls')),
    path('', include('apps.reportes.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/consorcios/models.py
from django.db import models
from django.utils.text import slugify


class Consorcio(models.Model):

    nombre = models.CharField(
        'Consorcio', max_length=255, unique=True
    )
    slug = models.SlugField(
        'Slug', max_length=255, unique=True
    )

    class Meta:

        verbose_name = 'Consorcio'
        verbose_name_plural = 'Consorcios'

    def save(self, *args, **kwargs):
        self.slug = slugify(self.nombre)
        super(Consorcio, self).save(*args, **kwargs)

    def __str__(self):
        return self.nombre


class Sector(models.Model):

    consorcio = models.ForeignKey(
        Consorcio, on_delete=models.CASCADE, verbose_name='consorcio')
    nombre = models.CharField(
        'Sector', max_length=255
    )
    slug = models.SlugField(
        'Slug', max_length=255, blank=True, null=True
    )

    class Meta:

        unique_together = ['consorcio', 'nombre']
        verbose_name = 'Sector'
        verbose_name_plural = 'Sectores'

    def save(self, *args, **kwargs):
        self.slug = slugify(self.consorcio) + '-' + slugify(self.nombre)
        super(Sector, self).save(*args, **kwargs)

    def __str__(self):
        return self.nombre

apps/consorcios/forms.py
from django import forms
from django.contrib.auth import authenticate


class LoginForm(forms.Form):

    username = forms.CharField(
        label='Usuario',
        required=True,
        widget=forms.TextInput(
            attrs={
                'class': 'form-control text-center',
                'placeholder': 'Usuario',
                'autocomplete': 'off',
            }
        ))
    password = forms.CharField(
        label='Contraseña',
        required=True,
        widget=forms.PasswordInput(
            attrs={
                'class': 'form-control text-center',
                'placeholder': 'Contraseña',
                'autocomplete': 'off',
            }
        ))

    def clean(self):
        username = self.cleaned_data['username']
        password = self.cleaned_data['password']

        if not authenticate(username=username, password=password):
            raise forms.ValidationError(
                'Usuario o Contraseña Incorrecta'
            )

        return self.cleaned_data

apps/consorcios/views.py
from django.urls import reverse_lazy
from django.shortcuts import render
from django.views.generic.edit import FormView
from django.views.generic import ListView, DetailView, TemplateView, View
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect
from .models import Consorcio, Sector

from .forms import LoginForm


class Home(TemplateView):
    template_name = "home.html"


class LoginView(FormView):
    template_name = 'login.html'
    form_class = LoginForm
    success_url = reverse_lazy('home')

    def form_valid(self, form):
        user = authenticate(
            username=form.cleaned_data['username'],
            password=form.cleaned_data['password']
        )
        login(self.request, user)
        return super(LoginView, self).form_valid(form)


class Consorcios(ListView):
    model = Consorcio
    template_name = "crear/consorcios.html"

    def get_context_data(self, **kwargs):
        consorcios = super().get_context_data(**kwargs)
        context = {
            'consorcios': consorcios['object_list'],
        }
        return context


class Sectores(DetailView):
    model = Consorcio
    template_name = "crear/sectores.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        consorcio = self.get_object()
        sectores = Sector.objects.filter(consorcio=consorcio.pk)
        context = {
            'consorcio': consorcio,
            'sectores': sectores,
        }
        return context


class LogoutView(View):
    def get(self, request, *args, **kargs):
        logout(request)
        return HttpResponseRedirect(reverse_lazy('consorcios_app:login'))

apps/reportes/views.py
from django.urls import reverse_lazy, reverse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect, JsonResponse, HttpResponse
from django.views.generic.edit import CreateView
from django.views.generic import ListView, DetailView, TemplateView, View

from apps.consorcios.models import Consorcio, Sector
from apps.cuestionario.models import Cuestionario, Pregunta
from .models import Reporte, Respuesta, Unidad, Obras, ImagenRespuesta

from .forms import ReporteForm, RespuestaForm, RespuestaFormSet, UnidadFormSet, ObrasFormSet, ImagenRespuestaFormSet

from datetime import date
from django.utils import timezone

# import os
# from django.conf import settings
# from django.template import Context
# from django.template.loader import get_template
# from xhtml2pdf import pisa


class ReporteView(CreateView):
    model = Reporte
    form_class = ReporteForm
    template_name = "crear/reporte.html"
    success_url = reverse_lazy('home')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        slug_sector = self.kwargs.get('slug')
        sector = Sector.objects.get(slug=slug_sector)
        cuestionario = Cuestionario.objects.get(sector=sector.id)
        preguntas = Pregunta.objects.filter(
            cuestionario=cuestionario.pk,
            estado=True,
            prox_visita__lte=timezone.now()
        ) | Pregunta.objects.filter(
            cuestionario=cuestionario.pk,
            estado=True,
            prox_visita=None
        )
        context['sector'] = sector
        context['preguntas'] = preguntas
        if "respuesta_formset" not in context:
            context['respuesta_formset'] = RespuestaFormSet(
                queryset=Respuesta.objects.none(),
            )
        return context

    def post(self, request, *args, **kwargs):
        self.object = None
        form = self.get_form()
        slug_sector = self.kwargs.get('slug')
        sector = Sector.objects.get(slug=slug_sector)
        respuesta_formset = RespuestaFormSet(request.POST, request.FILES)
        if respuesta_formset.is_valid() and form.is_valid():
            return self.form_valid(form, respuesta_formset, sector)
        else:
            return self.form_invalid(form, respuesta_formset)

    def form_invalid(self, form, respuesta_formset):
        return self.render_to_response(
            self.get_context_data(
                form=form,
                respuesta_formset=respuesta_formset,
            )
        )

    def form_valid(self, form, respuesta_formset, sector):
        reporte = form.save(commit=False)
        reporte.user = self.request.user
        reporte.consorcio = sector.consorcio
        reporte.sector = sector
        reporte.save()
        instancesResp = respuesta_formset.save(commit=False)
        for instanceResp in instancesResp:
            if instanceResp.respuesta != None:
                instanceResp.reporte = reporte
                instanceResp.save()
                pregunta = Pregunta.objects.get(id=instanceResp.pregunta.id)
                pregunta.ultima_visita = date.today()
                pregunta.save()
        # intancesImg = imagen_respuesta_formset.save(commit=False)
        # for instanceImg in intancesImg:
        #     if instanceImg.imagen != None:
        #         instanceImg.save()
        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self):
        sector = Sector.objects.get(slug=self.kwargs.get('slug'))
        return reverse('consorcios_app:sectores-list', kwargs={'slug': sector.consorcio.slug})


class ReporteUnidadView(CreateView):
    model = Reporte
    form_class = ReporteForm
    template_name = "crear/reporte-unidad.html"
    success_url = reverse_lazy('home')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        slug_sector = self.kwargs.get('slug')
        sector = Sector.objects.get(slug=slug_sector)
        context['sector'] = sector
        if "unidad_formset" not in context:
            context['unidad_formset'] = UnidadFormSet(
                queryset=Unidad.objects.none(),
            )
        return context

    def post(self, request, *args, **kwargs):
        self.object = None
        form = self.get_form()
        slug_sector = self.kwargs.get('slug')
        sector = Sector.objects.get(slug=slug_sector)
        unidad_formset = UnidadFormSet(request.POST, request.FILES)
        if unidad_formset.is_valid() and form.is_valid():
            return self.form_valid(form, unidad_formset, sector)
        else:
            return self.form_invalid(form, unidad_formset)

    def form_invalid(self, form, unidad_formset):
        return self.render_to_response(
            self.get_context_data(
                form=form,
                unidad_formset=unidad_formset,
            )
        )

    def form_valid(self, form, unidad_formset, sector):
        if Reporte.objects.filter(
            consorcio=sector.consorcio,
            sector=sector,
            creacion=date.today(),
        ).exists():
            getReporte = Reporte.objects.get(
                consorcio=sector.consorcio,
                sector=sector,
                creacion=date.today(),
            )
            reporte = getReporte
        else:
            reporte = form.save(commit=False)
            reporte.user = self.request.user
            reporte.consorcio = sector.consorcio
            reporte.sector = sector
            reporte.save()
        instancesUnit = unidad_formset.save(commit=False)
        for instanceUnit in instancesUnit:
            if instanceUnit.unidad != None:
                instanceUnit.reporte = reporte
                instanceUnit.save()
        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self):
        sector = Sector.objects.get(slug=self.kwargs.get('slug'))
        return reverse('consorcios_app:sectores-list', kwargs={'slug': sector.consorcio.slug})


class ReporteObraView(CreateView):
    model = Reporte
    form_class = ReporteForm
    template_name = "crear/obras-sectores-comunes.html"
    success_url = reverse_lazy('home')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        slug_sector = self.kwargs.get('slug')
        sector = Sector.objects.get(slug=slug_sector)
        context['sector'] = sector
        if "obras_formset" not in context:
            context['obras_formset'] = ObrasFormSet(
                queryset=Obras.objects.none(),
            )
        return context

    def post(self, request, *args, **kwargs):
        self.object = None
        form = self.get_form()
        slug_sector = self.kwargs.get('slug')
        sector = Sector.objects.get(slug=slug_sector)
        obras_formset = ObrasFormSet(request.POST, request.FILES)
        if obras_formset.is_valid() and form.is_valid():
            return self.form_valid(form, obras_formset, sector)
        else:
            return self.form_invalid(form, obras_formset)

    def form_invalid(self, form, obras_formset):
        return self.render_to_response(
            self.get_context_data(
                form=form,
                obras_formset=obras_formset,
            )
        )

    def form_valid(self, form, obras_formset, sector):
        if Reporte.objects.filter(
            consorcio=sector.consorcio,
            sector=sector,
            creacion=date.today(),
        ).exists():
            getReporte = Reporte.objects.get(
                consorcio=sector.consorcio,
                sector=sector,
                creacion=date.today(),
            )
            reporte = getReporte
        else:
            reporte = form.save(commit=False)
            reporte.user = self.request.user
            reporte.consorcio = sector.consorcio
            reporte.sector = sector
            reporte.save()
        instancesObra = obras_formset.save(commit=False)
        for instanceObra in instancesObra:
            if instanceObra.obra != None:
                instanceObra.reporte = reporte
                instanceObra.save()
        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self):
        sector = Sector.objects.get(slug=self.kwargs.get('slug'))
        return reverse('consorcios_app:sectores-list', kwargs={'slug': sector.consorcio.slug})


class ConsorciosReportes(ListView):
    model = Consorcio
    template_name = "reportes/consorcios.html"

    def get_context_data(self, **kwargs):
        consorcios = super().get_context_data(**kwargs)
        context = {
            'consorcios': consorcios['object_list'],
        }
        return context


class ReportesList(DetailView):
    model = Consorcio
    template_name = "reportes/reporte-list.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        consorcio = self.get_object()
        reportesall = Reporte.objects.filter(
            consorcio=consorcio.pk,
        ).values_list('creacion', flat=True).distinct()
        reportes = Reporte.objects.filter(
            consorcio=consorcio.pk,
        ).values_list('creacion', flat=True).distinct()
        filterY = self.request.GET.get('filterY')
        filterM = self.request.GET.get('filterM')
        if filterY and not filterM:
            reportes = Reporte.objects.filter(
                consorcio=consorcio.pk,
                creacion__year=filterY,
            ).values_list('creacion', flat=True).distinct()
        if filterY and filterM:
            reportes = Reporte.objects.filter(
                consorcio=consorcio.pk,
                creacion__year=filterY,
                creacion__month=filterM
            ).values_list('creacion', flat=True).distinct()
        context = {
            'consorcio': consorcio,
            'reportes': reportes,
            'reportesall': reportesall,
        }
        return context

templates/reportes/consorcios.html
{% extends 'layout.html' %}
{% load static %}

{% block title %}Consorcios{% endblock title %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col">
      <h1 class="text-center display-6 mb-3">Consorcios</h1>
    </div>
  </div>
  <div class="row">
    <div class="col-10 offset-1 col-sm-8 offset-sm-2 col-md-6 offset-md-3 col-lg-4 offset-lg-4">
      <div class="d-grid gap-2">
        
        {% for c in consorcios %}
  
        <a href="{% url 'reportes_app:reportes-list' c.slug %}" class="btn btn-outline-primary" type="button">{{ c }}</a>
          
        {% endfor %}
          
      </div>
    </div>
  </div>
  <div class="text-end mt-3">
    <a class="btn btn-primary" href="javascript:history.back()">Atrás</a>
  </div>
</div>
{% endblock content %}

templates/reportes/reporte-full.html
{% load static %}

<!DOCTYPE html>
<html lang="es">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
  <title>Reporte</title>
  <link rel="stylesheet" href="{% static 'libs/bootstrap/css/bootstrap.min.css' %}">
  <style>
    p {
      margin: 0;
    }
    img {
      break-inside:avoid;
    }
  </style>
</head>
<body class="py-5">
  <div class="d-grid fixed-top">
    <button id="download-report" class="btn btn-success btn-sm d-none" onclick="ReportePDF()"><strong>Descargar Reporte</strong></button>
    <button class="btn btn-success btn-sm d-none" onclick="ReportePDF2()"><strong>Descargar Reporte 02</strong></button>
  </div>
  <main class="container">
    <div class="d-flex justify-content-between">
      <img class="img-fluid" src="{% static 'img/logo-reporte.png' %}" style="max-width: 50%;">
      <img class="img-fluid" src="{% static 'img/logo-reporte2.png' %}" style="max-width: 50%;">
    </div>
    <p class="text-end mb-3">Reporte hecho por: {{ byuser.first_name }} {{ byuser.last_name }}</p>
    
    <p class="mt-3 text-end">Señores</p>
    <p class="text-end"><strong>{{ consorcio.nombre }}</strong></p>
    <p class="text-end mb-3">PRESENTE</p>
    
    <h2 class="text-center text-uppercase rounded bg-primary bg-gradient text-white p-3 mb-3">Informe de visita<br>{{ fecha|date:'j \d\e F \d\e Y' }}</h2>
    
    <p class="text-end mb-3">Buenos Aires, {{ fecha|date:'j \d\e F \d\e Y' }}</p>
    
    <p class="mb-3">Nos complace dirigirnos a usted a fin de poner a consideración el informe de la visita realizada el dia {{ fecha|date:'j \d\e F \d\e Y' }}</p>
    
    <div id="content">
      
      
    </div>
    <div id="elementH"></div>

    <!-- <div class="text-end mt-3">
      <a class="btn btn-primary" href="javascript:history.back()">Atrás</a>
    </div> -->
  </main>
  <script src="{% static 'libs/jquery/jquery-3.6.1.min.js' %}"></script>
  <script type="text/javascript">
    $(document).ready(function() {
      var protocol = window.location.protocol
      var host = window.location.host
      {% for r in reportes %}
        $('#content').append('<div id="{{r.sector|lower|cut:" "}}"></div>')
        var url = protocol+'//'+host+'/reportes/{{r.sector.slug}}-{{fecha|date:"Y-m-d"}}/reporte'
        $('#{{r.sector|lower|cut:" "}}').load(url+' #report-{{r.sector|lower|cut:" "}}');
      {% endfor %}
    });
  </script>
  <script src="{% static 'libs/html2pdf/html2pdf.min.js' %}"></script>
  <script>
    window.onload = function() {
      $('#download-report').removeClass('d-none')
    }
    function ReportePDF() {
      const ReportePDF = document.querySelector('main') // <-- Aquí puedes elegir cualquier elemento del DOM
        html2pdf()
        .set({
          margin: 0.5,
          filename: '{{ consorcio.slug }}-{{ fecha|date:"d-m-Y" }}.pdf',
          image: {
            type: 'jpeg',
              quality: 0.98
          },
          html2canvas: {
              scale: 1, // A mayor escala, mejores gráficos, pero más peso
              letterRendering: true,
          },
          jsPDF: {
              unit: "in",
              format: "letter",
              orientation: 'portrait' // landscape o portrait
          }
        })
        .from(ReportePDF)
        .save()
        .catch(err => console.log(err))
    }
  </script>
  <script src="{% static 'libs/jspdf/jspdf.min.js' %}"></script>
  <script>
    function ReportePDF2() {
      var doc = new jsPDF();
      doc.fromHTML(
        $('main').html(),
        15,
        15,
        {
          'width': 170
        },
        function(dispose) {
          doc.save('{{ consorcio.slug }}-{{ fecha|date:"d-m-Y" }}.pdf')
        }
      )
    }
  </script>
</body>
</html>

templates/reportes/reporte-list.html
{% extends 'layout.html' %}
{% load static %}

{% block title %}Reportes{% endblock title %}

{% block stylesheet %}

{% endblock stylesheet %}

{% block css %}
<style>
  
</style>
{% endblock css %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col">
      <h1 class="text-center display-6 mb-3">{{ consorcio.nombre }}</h1>
    </div>
  </div>

  <div class="row">
    <div class="col-10 offset-1 col-sm-8 offset-sm-2 col-md-6 offset-md-3 col-lg-4 offset-lg-4">
      <form action="{% url 'reportes_app:reportes-list' consorcio.slug %}" method="GET">
        <div class="input-group">
          <select class="form-select" id="filterY" name="filterY">
            <option selected value="">Año</option>
          </select>
          <select class="form-select" id="filterM" name="filterM">
            <option selected value="">Mes</option>
            <option value="01">Enero</option>
            <option value="02">Febrero</option>
            <option value="03">Marzo</option>
            <option value="04">Abril</option>
            <option value="05">Mayo</option>
            <option value="06">Junio</option>
            <option value="07">Julio</option>
            <option value="08">Agosto</option>
            <option value="09">Septiembre</option>
            <option value="10">Octubre</option>
            <option value="11">Noviembre</option>
            <option value="12">Diciembre</option>
          </select>
          <button type="submit" class="btn btn-primary">Buscar</button>
        </div>
        <p class="small">Seleccionar Año y Mes para filtrar</p>
      </form>
      <div class="d-grid gap-2">
        
        
        {% if reportes|length == 0 %}
        <div class="alert alert-info text-center">
          No hay reportes para este consorcio.
        </div>
        {% endif %}        
        
        {% for r in reportes %}
        
        <a href="{% url 'reportes_app:reporte-sectores' slug=consorcio.slug date=r %}" class="btn btn-outline-primary" type="button">Reporte {{ r|date:'d-M-Y' }}</a>
        
        {% endfor %}
        
      </div>
    </div>
  </div>
  <div class="text-end mt-3">
    <a class="btn btn-primary" href="javascript:history.back()">Atrás</a>
  </div>
</div>
{% endblock content %}

{% block js %}
<script>
  var anios = []
  {% for rall in reportesall %}
    anios.push("{{ rall|date:'Y' }}")
  {% endfor %}
  for (let i = 0; i < anios.length; i++) {
    $('#filterY').append('<option value="'+anios+'">'+anios+'</option>')
  }
</script>
{% endblock js %}

templates/reportes/sectores-list.html
{% extends 'layout.html' %}
{% load static %}

{% block title %}{{ consorcio.nombre }}{% endblock title %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col">
      <h1 class="text-center display-6 mb-3">Reportes<br><strong></strong>{{ consorcio.nombre }}</strong><br>{{ fecha|date:'j \d\e F \d\e Y' }}</h1>
    </div>
  </div>
  <div class="row">
    <div class="col-10 offset-1 col-sm-8 offset-sm-2 col-md-6 offset-md-3 col-lg-4 offset-lg-4">
      <div class="d-grid gap-2">
        
        <a href="{% url 'reportes_app:reporte-full' slug=consorcio.slug date=fecha %}" class="btn btn-primary mb-4" type="button">Reporte Completo</a>
        
        {% for r in reportes %}
  
        <a href="{% url 'reportes_app:reporte' r.slug %}" class="btn btn-outline-primary" type="button">{{ r.sector }}</a>
        
        {% endfor %}
        
      </div>
    </div>
  </div>
  <div class="text-end mt-3">
    <a class="btn btn-primary" href="javascript:history.back()">Atrás</a>
  </div>
</div>
{% endblock content %}

templates/reportes/sectores.html
{% extends 'layout.html' %}
{% load static %}

{% block title %}{{ consorcio.nombre }}{% endblock title %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col">
      <h6 class="text-center">Crear Reporte</h6>
      <h1 class="text-center display-6 mb-3">{{ consorcio.nombre }}</h1>
    </div>
  </div>
  <div class="row">
    <div class="col-10 offset-1 col-sm-8 offset-sm-2 col-md-6 offset-md-3 col-lg-4 offset-lg-4">
      <div class="d-grid gap-2">
        
        {% for s in sectores %}
  
        <a href="{% url 'reportes_app:reporte' s.slug %}" class="btn btn-outline-primary" type="button">{{ s }}</a>
          
        {% endfor %}
          
      </div>
    </div>
  </div>
  <div class="text-end mt-3">
    <a class="btn btn-primary" href="javascript:history.back()">Atrás</a>
  </div>
</div>
{% endblock content %}