apps/consorcios/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

from . import views

app_name = "consorcios_app"

urlpatterns = [
    path(
        'accounts/login/',
        views.LoginView.as_view(),
        name='login',
    ),
    path(
        'logout',
        views.LogoutView.as_view(),
        name='logout',
    ),
    path(
        'crear-reporte/consorcios',
        login_required(views.Consorcios.as_view()),
        name='consorcios-list',
    ),
    path(
        'crear-reporte/<slug:slug>',
        login_required(views.Sectores.as_view()),
        name='sectores-list',
    ),
]

apps/reportes/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

from . import views

app_name = "reportes_app"

urlpatterns = [
    path(
        'crear-reporte/<slug:slug>/crear',
        login_required(views.ReporteView.as_view()),
        name='reporte-add',
    ),
    path(
        'crear-reporte/<slug:slug>/unidad',
        login_required(views.ReporteUnidadView.as_view()),
        name='reporte-unidad-add',
    ),
    path(
        'crear-reporte/<slug:slug>/obra',
        login_required(views.ReporteObraView.as_view()),
        name='reporte-obra-add',
    ),
    path(
        'reportes/consorcios',
        views.ConsorciosReportes.as_view(),
        name='reportes-consorcios-list',
    ),
    path(
        'reportes/<slug:slug>/',
        views.ReportesList.as_view(),
        name='reportes-list',
    ),
    path(
        'reportes/<str:slug>/<str:date>/',
        views.ReporteSectores.as_view(),
        name='reporte-sectores',
    ),
    path(
        'reportes/<slug:slug>/reporte',
        views.ReporteDetail.as_view(),
        name='reporte',
    ),
    path(
        'reportes/<str:slug>/<str:date>/reporte',
        views.ReporteFull.as_view(),
        name='reporte-full',
    ),
    # path(
    #     'reportes/<str:slug>/<str:date>/',
    #     views.ReporteDetail.as_view(),
    #     name='reporte',
    # ),
]

confiarbr/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.decorators import login_required

from apps.consorcios.views import Home


urlpatterns = [
    path('admin/', admin.site.urls),
    path('chaining/', include('smart_selects.urls')),

    path(
        '',
        Home.as_view(),
        name='home',
    ),
    
    path('', include('apps.consorcios.urls')),
    path('', include('apps.reportes.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/reportes/forms.py
from django import forms
from django.forms import modelformset_factory, inlineformset_factory

from .models import Reporte, Respuesta, Unidad, ImagenRespuesta, Obras


class ReporteForm(forms.ModelForm):
    class Meta:
        model = Reporte
        fields = []


class RespuestaForm(forms.ModelForm):
    class Meta:
        model = Respuesta
        fields = [
            'pregunta',
            'respuesta',
            'observaciones',
            'imagen1',
            'imagen2',
            'imagen3',
            'imagen4',
        ]
        widgets = {
            'pregunta': forms.HiddenInput(
                attrs={
                    'class': 'form-control disabled',
                }
            ),
            'respuesta': forms.Select(
                attrs={
                    'class': 'form-select',
                }
            ),
            'observaciones': forms.Textarea(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Observaciones',
                    'rows': '2',
                    'style': 'resize: none;'
                }
            ),
            'imagen1': forms.FileInput(
                attrs={
                    'class': 'form-control',
                }
            ),
            'imagen2': forms.FileInput(
                attrs={
                    'class': 'form-control',
                }
            ),
            'imagen3': forms.FileInput(
                attrs={
                    'class': 'form-control',
                }
            ),
            'imagen4': forms.FileInput(
                attrs={
                    'class': 'form-control',
                }
            ),
        }


RespuestaFormSet = modelformset_factory(
    Respuesta,
    form=RespuestaForm,
    extra=0,
)


class UnidadForm(forms.ModelForm):
    class Meta:
        model = Unidad
        fields = [
            'unidad',
            'observaciones',
            'imagen1',
            'imagen2',
            'imagen3',
            'imagen4',
        ]
        widgets = {
            'unidad': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Unidad',
                }
            ),
            'observaciones': forms.Textarea(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Observaciones',
                    'rows': '2',
                    'style': 'resize: none;'
                }
            ),
            'imagen1': forms.FileInput(
                attrs={
                    'class': 'form-control',
                }
            ),
            'imagen2': forms.FileInput(
                attrs={
                    'class': 'form-control',
                }
            ),
            'imagen3': forms.FileInput(
                attrs={
                    'class': 'form-control',
                }
            ),
            'imagen4': forms.FileInput(
                attrs={
                    'class': 'form-control',
                }
            ),
        }


UnidadFormSet = modelformset_factory(
    Unidad,
    form=UnidadForm,
    extra=1,
)


class ObrasForm(forms.ModelForm):
    class Meta:
        model = Obras
        fields = [
            'obra',
            'observaciones',
            'imagen1',
            'imagen2',
            'imagen3',
            'imagen4',
        ]
        widgets = {
            'obra': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Obra en sector común',
                }
            ),
            'observaciones': forms.Textarea(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Observaciones',
                    'rows': '2',
                    'style': 'resize: none;'
                }
            ),
            'imagen1': forms.FileInput(
                attrs={
                    'class': 'form-control',
                }
            ),
            'imagen2': forms.FileInput(
                attrs={
                    'class': 'form-control',
                }
            ),
            'imagen3': forms.FileInput(
                attrs={
                    'class': 'form-control',
                }
            ),
            'imagen4': forms.FileInput(
                attrs={
                    'class': 'form-control',
                }
            ),
        }


ObrasFormSet = modelformset_factory(
    Obras,
    form=ObrasForm,
    extra=1,
)


class ImagenRespuestaForm(forms.ModelForm):
    class Meta:
        model = ImagenRespuesta
        fields = [
            'respuesta',
            'imagen',
        ]
        widgets = {
            'respuesta': forms.HiddenInput(
                attrs={
                    'class': 'form-control disabled',
                }
            ),
            'imagen': forms.FileInput(
                attrs={
                    'class': 'form-control',
                }
            ),
        }


ImagenRespuestaFormSet = inlineformset_factory(
    Respuesta,
    ImagenRespuesta,
    form=ImagenRespuestaForm,
    extra=0,
)

apps/reportes/views.py
from django.urls import reverse_lazy, reverse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect, JsonResponse, HttpResponse
from django.views.generic.edit import CreateView
from django.views.generic import ListView, DetailView, TemplateView, View

from apps.consorcios.models import Consorcio, Sector
from apps.cuestionario.models import Cuestionario, Pregunta
from .models import Reporte, Respuesta, Unidad, Obras, ImagenRespuesta

from .forms import ReporteForm, RespuestaForm, RespuestaFormSet, UnidadFormSet, ObrasFormSet, ImagenRespuestaFormSet

from datetime import date
from django.utils import timezone

# import os
# from django.conf import settings
# from django.template import Context
# from django.template.loader import get_template
# from xhtml2pdf import pisa


class ReporteView(CreateView):
    model = Reporte
    form_class = ReporteForm
    template_name = "crear/reporte.html"
    success_url = reverse_lazy('home')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        slug_sector = self.kwargs.get('slug')
        sector = Sector.objects.get(slug=slug_sector)
        cuestionario = Cuestionario.objects.get(sector=sector.id)
        preguntas = Pregunta.objects.filter(
            cuestionario=cuestionario.pk,
            estado=True,
            prox_visita__lte=timezone.now()
        ) | Pregunta.objects.filter(
            cuestionario=cuestionario.pk,
            estado=True,
            prox_visita=None
        )
        context['sector'] = sector
        context['preguntas'] = preguntas
        if "respuesta_formset" not in context:
            context['respuesta_formset'] = RespuestaFormSet(
                queryset=Respuesta.objects.none(),
            )
        return context

    def post(self, request, *args, **kwargs):
        self.object = None
        form = self.get_form()
        slug_sector = self.kwargs.get('slug')
        sector = Sector.objects.get(slug=slug_sector)
        respuesta_formset = RespuestaFormSet(request.POST, request.FILES)
        if respuesta_formset.is_valid() and form.is_valid():
            return self.form_valid(form, respuesta_formset, sector)
        else:
            return self.form_invalid(form, respuesta_formset)

    def form_invalid(self, form, respuesta_formset):
        return self.render_to_response(
            self.get_context_data(
                form=form,
                respuesta_formset=respuesta_formset,
            )
        )

    def form_valid(self, form, respuesta_formset, sector):
        reporte = form.save(commit=False)
        reporte.user = self.request.user
        reporte.consorcio = sector.consorcio
        reporte.sector = sector
        reporte.save()
        instancesResp = respuesta_formset.save(commit=False)
        for instanceResp in instancesResp:
            if instanceResp.respuesta != None:
                instanceResp.reporte = reporte
                instanceResp.save()
                pregunta = Pregunta.objects.get(id=instanceResp.pregunta.id)
                pregunta.ultima_visita = date.today()
                pregunta.save()
        # intancesImg = imagen_respuesta_formset.save(commit=False)
        # for instanceImg in intancesImg:
        #     if instanceImg.imagen != None:
        #         instanceImg.save()
        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self):
        sector = Sector.objects.get(slug=self.kwargs.get('slug'))
        return reverse('consorcios_app:sectores-list', kwargs={'slug': sector.consorcio.slug})


class ReporteUnidadView(CreateView):
    model = Reporte
    form_class = ReporteForm
    template_name = "crear/reporte-unidad.html"
    success_url = reverse_lazy('home')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        slug_sector = self.kwargs.get('slug')
        sector = Sector.objects.get(slug=slug_sector)
        context['sector'] = sector
        if "unidad_formset" not in context:
            context['unidad_formset'] = UnidadFormSet(
                queryset=Unidad.objects.none(),
            )
        return context

    def post(self, request, *args, **kwargs):
        self.object = None
        form = self.get_form()
        slug_sector = self.kwargs.get('slug')
        sector = Sector.objects.get(slug=slug_sector)
        unidad_formset = UnidadFormSet(request.POST, request.FILES)
        if unidad_formset.is_valid() and form.is_valid():
            return self.form_valid(form, unidad_formset, sector)
        else:
            return self.form_invalid(form, unidad_formset)

    def form_invalid(self, form, unidad_formset):
        return self.render_to_response(
            self.get_context_data(
                form=form,
                unidad_formset=unidad_formset,
            )
        )

    def form_valid(self, form, unidad_formset, sector):
        if Reporte.objects.filter(
            consorcio=sector.consorcio,
            sector=sector,
            creacion=date.today(),
        ).exists():
            getReporte = Reporte.objects.get(
                consorcio=sector.consorcio,
                sector=sector,
                creacion=date.today(),
            )
            reporte = getReporte
        else:
            reporte = form.save(commit=False)
            reporte.user = self.request.user
            reporte.consorcio = sector.consorcio
            reporte.sector = sector
            reporte.save()
        instancesUnit = unidad_formset.save(commit=False)
        for instanceUnit in instancesUnit:
            if instanceUnit.unidad != None:
                instanceUnit.reporte = reporte
                instanceUnit.save()
        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self):
        sector = Sector.objects.get(slug=self.kwargs.get('slug'))
        return reverse('consorcios_app:sectores-list', kwargs={'slug': sector.consorcio.slug})


class ReporteObraView(CreateView):
    model = Reporte
    form_class = ReporteForm
    template_name = "crear/obras-sectores-comunes.html"
    success_url = reverse_lazy('home')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        slug_sector = self.kwargs.get('slug')
        sector = Sector.objects.get(slug=slug_sector)
        context['sector'] = sector
        if "obras_formset" not in context:
            context['obras_formset'] = ObrasFormSet(
                queryset=Obras.objects.none(),
            )
        return context

    def post(self, request, *args, **kwargs):
        self.object = None
        form = self.get_form()
        slug_sector = self.kwargs.get('slug')
        sector = Sector.objects.get(slug=slug_sector)
        obras_formset = ObrasFormSet(request.POST, request.FILES)
        if obras_formset.is_valid() and form.is_valid():
            return self.form_valid(form, obras_formset, sector)
        else:
            return self.form_invalid(form, obras_formset)

    def form_invalid(self, form, obras_formset):
        return self.render_to_response(
            self.get_context_data(
                form=form,
                obras_formset=obras_formset,
            )
        )

    def form_valid(self, form, obras_formset, sector):
        if Reporte.objects.filter(
            consorcio=sector.consorcio,
            sector=sector,
            creacion=date.today(),
        ).exists():
            getReporte = Reporte.objects.get(
                consorcio=sector.consorcio,
                sector=sector,
                creacion=date.today(),
            )
            reporte = getReporte
        else:
            reporte = form.save(commit=False)
            reporte.user = self.request.user
            reporte.consorcio = sector.consorcio
            reporte.sector = sector
            reporte.save()
        instancesObra = obras_formset.save(commit=False)
        for instanceObra in instancesObra:
            if instanceObra.obra != None:
                instanceObra.reporte = reporte
                instanceObra.save()
        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self):
        sector = Sector.objects.get(slug=self.kwargs.get('slug'))
        return reverse('consorcios_app:sectores-list', kwargs={'slug': sector.consorcio.slug})


class ConsorciosReportes(ListView):
    model = Consorcio
    template_name = "reportes/consorcios.html"

    def get_context_data(self, **kwargs):
        consorcios = super().get_context_data(**kwargs)
        context = {
            'consorcios': consorcios['object_list'],
        }
        return context


class ReportesList(DetailView):
    model = Consorcio
    template_name = "reportes/reporte-list.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        consorcio = self.get_object()
        reportesall = Reporte.objects.filter(
            consorcio=consorcio.pk,
        ).values_list('creacion', flat=True).distinct()
        reportes = Reporte.objects.filter(
            consorcio=consorcio.pk,
        ).values_list('creacion', flat=True).distinct()
        filterY = self.request.GET.get('filterY')
        filterM = self.request.GET.get('filterM')
        if filterY and not filterM:
            reportes = Reporte.objects.filter(
                consorcio=consorcio.pk,
                creacion__year=filterY,
            ).values_list('creacion', flat=True).distinct()
        if filterY and filterM:
            reportes = Reporte.objects.filter(
                consorcio=consorcio.pk,
                creacion__year=filterY,
                creacion__month=filterM
            ).values_list('creacion', flat=True).distinct()
        context = {
            'consorcio': consorcio,
            'reportes': reportes,
            'reportesall': reportesall,
        }
        return context

templates/home.html
{% extends 'layout.html' %}
{% load static %}

{% block title %}Inicio{% endblock title %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col">
      <h6 class="text-center display-6">Confiar BR</h6>
    </div>
  </div>
  <div class="row mt-5">
    <div class="col-10 offset-1 col-sm-8 offset-sm-2 col-md-6 offset-md-3 col-lg-4 offset-lg-4">
      <div class="d-grid gap-2">
  
        <a href="{% url 'consorcios_app:consorcios-list' %}" class="btn btn-outline-primary" type="button">Crear Reporte</a>
        <a href="{% url 'reportes_app:reportes-consorcios-list' %}" class="btn btn-outline-primary" type="button">Ver Reportes</a>
          
      </div>
    </div>
  </div>
</div>
{% endblock content %}

templates/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="es">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no, maximum-scale=1.0">
  
  <title>{% block title %}{% endblock title %} | ConfiarBR</title>
  
  {% block stylesheet %}{% endblock stylesheet %}
  
  <!-- Main CSS -->
  <link rel="stylesheet" href="{% static 'libs/bootstrap/css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body style="min-height: 100vh;">
  {% block css %}{% endblock css %}
  
  <nav class="navbar navbar-expand-lg bg-dark navbar-dark fixed-top">
    <div class="container">
      <a class="navbar-brand" href="{% url 'home' %}">
        <img class="w-50" src="{% static 'img/logo-blanco.png' %}" alt="">
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
          {% if user.is_authenticated %}
          <li class="nav-item text-end mt-3 mt-lg-0">
            <span class="nav-link">
              Usuario: {{ request.user.username }}
            </span>
          </li>
          <li class="nav-item text-end">
            <a class="nav-link" href="{% url 'consorcios_app:logout' %}">Logout</a>
          </li>
          {% else %}
          <li class="nav-item text-end">
            <a class="nav-link" href="{% url 'consorcios_app:login' %}">Login</a>
          </li>
          {% endif%}
        </ul>
      </div>
    </div>
  </nav>
  
  <main class="pb-5" style="padding-top: 80px;">
    {% block content %}{% endblock content %}
  </main>
  
  <!-- scripts -->
  <script src="{% static 'libs/bootstrap/js/bootstrap.bundle.js' %}"></script>
  <script src="{% static 'libs/jquery/jquery-3.6.1.min.js' %}"></script>
  {% block js %}{% endblock js %}
</body>
</html>

templates/login.html
{% extends 'layout.html' %}
{% load static %}

{% block title %}Login{% endblock title %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col">
      <h6 class="text-center display-6">Confiar BR</h6>
      <h6 class="text-center display-6">Iniciar Sesión</h6>
    </div>
  </div>
  <div class="row mt-3">
    <div class="col-10 offset-1 col-sm-8 offset-sm-2 col-md-6 offset-md-3 col-lg-4 offset-lg-4 col-xl-2 offset-xl-5">
      <form id="login" method="POST">
        {% csrf_token %}
        {% if form.non_field_errors %}
          {% for error in form.non_field_errors %}
          <div class="alert alert-danger text-center mt-3 mb-0 py-2" role="alert">
            Usuario o Contraseña incorrecta
          </div>
          {% endfor %}
        {% endif %}
        <div class="content-input mb-2">
          {{ form.username }}
        </div>
        <div class="content-input mb-0">
          {{ form.password }}
        </div>
        <div class="text-center">
          <button type="submit" class="btn btn-primary mt-3">Iniciar sesión</button>
        </div>
      </form>
    </div>
  </div>
</div>
{% endblock content %}

templates/reporte.html
{% extends 'layout.html' %}
{% load static %}

{% block title %}Cuestionario{% endblock title %}

{% block stylesheet %}
<link rel="stylesheet" href="{% static 'libs/bs-stepper/bs-stepper.min.css' %}">
{% endblock stylesheet %}

{% block css %}
<style>
  .item {
    border: 1px solid var(--bs-primary);
    border-radius: 1rem;
  }
</style>
{% endblock css %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col">
      <h1 class="text-center display-6"><strong>Reporte</strong></h1>
      <h3 class="text-center">{{ sector.consorcio }} - {{ sector.nombre }}</h3>
    </div>
  </div>
  <div class="row">
    <div class="col-12 col-sm-8 offset-sm-2 col-md-6 offset-md-3">
      <form action="" method="post">
        {% csrf_token %}

        {{ respuesta_formset.management_form }}

        <div id="inputs_resp"></div>

        <div class="d-grid gap-2 mt-3">
          <button class="btn btn-primary" type="submit">Finalizar Reporte</button>
        </div>
      </form>
    </div>
  </div>
</div>
{% endblock content %}

{% block js %}
<script src="{% static 'libs/bs-stepper/bs-stepper.min.js' %}"></script>
<script>
  var preguntas = []
  var preguntas_id = []
  {% for p in preguntas %}
  preguntas.push('{{ p }}')
  preguntas_id.push('{{ p.id }}')
  {% endfor %}

  $('#id_form-TOTAL_FORMS').val(preguntas.length)
  
  for (let i = 0; i < preguntas.length; i++) {

    inputs = `
    <div class="item item-`+i+`-p mt-5 py-3 px-1">
      <p id="id_pregunta-`+i+`" class=""><strong>`+preguntas[i]+`</strong></p>
      <input type="hidden" name="form-`+i+`-pregunta" class="form-control disabled" id="id_form-`+i+`-pregunta" value="`+preguntas_id[i]+`">
      <div class="mb-3">
        <div class="form-check form-check-inline">
          <input class="form-check-input" type="radio" name="form-`+i+`-respuesta" id="id_form-`+i+`-respuesta" value="S">
          <label class="form-check-label" for="id_form-`+i+`-respuesta">SI</label>
        </div>
        <div class="form-check form-check-inline">
          <input class="form-check-input" type="radio" name="form-`+i+`-respuesta" id="id_form-`+i+`-respuesta" value="N">
          <label class="form-check-label" for="id_form-`+i+`-respuesta">NO</label>
        </div>
      </div>
      <label for="id_form-`+i+`-observaciones"><strong>Observaciones</strong></label>
      <textarea name="form-`+i+`-observaciones" rows="2" class="form-control" placeholder="Observaciones" style="resize: none;" id="id_form-`+i+`-observaciones"></textarea>
    </div>
    `
    $('#inputs_resp').append(inputs)

  }
</script>
{% endblock js %}

templates/reporte_imageformset.html
{% extends 'layout.html' %}
{% load static %}

{% block title %}Cuestionario{% endblock title %}

{% block stylesheet %}
<link rel="stylesheet" href="{% static 'libs/bs-stepper/bs-stepper.min.css' %}">
{% endblock stylesheet %}

{% block css %}
<style>
  .item {
    border: 1px solid var(--bs-primary);
    border-radius: 1rem;
  }
</style>
{% endblock css %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col">
      <h1 class="text-center display-6"><strong>Reporte</strong></h1>
      <h3 class="text-center">{{ sector.consorcio }} - {{ sector.nombre }}</h3>
    </div>
  </div>
  <div class="row">
    <div class="col-12 col-sm-8 offset-sm-2 col-md-6 offset-md-3">
      <form action="" method="post">
        {% csrf_token %}

        {{ respuesta_formset.management_form }}
        {{ imagen_respuesta_formset.management_form }}

        <div id="inputs_resp"></div>

        <div id="no-q" class="alert alert-info text-center d-none">
          No hay preguntas activas para este sector en esta fecha.
          <br>
          <br>
          Contacte al administrador.
        </div>

        <div id="btn-guardar" class="d-grid gap-2 mt-3">
          <button class="btn btn-primary" type="submit">Guardar</button>
        </div>
      </form>
    </div>
  </div>
</div>
{% endblock content %}

{% block js %}
<script src="{% static 'libs/bs-stepper/bs-stepper.min.js' %}"></script>
<script>
  var preguntas = []
  var preguntas_id = []
  {% for p in preguntas %}
  preguntas.push('{{ p }}')
  preguntas_id.push('{{ p.id }}')
  {% endfor %}

  if (preguntas.length == 0) {
    $('#no-q').removeClass('d-none')
    $('#btn-guardar').addClass('d-none')
  }

  $('#id_form-TOTAL_FORMS').val(preguntas.length)
  
  for (let i = 0; i < preguntas.length; i++) {

    var inputs = `
    <div id="item-`+i+`" class="item item-`+i+`-p mt-5 py-3 px-3">
      <p id="id_pregunta-`+i+`" class=""><strong>`+preguntas[i]+`</strong></p>
      <input type="hidden" name="form-`+i+`-pregunta" class="form-control disabled" id="id_form-`+i+`-pregunta" value="`+preguntas_id[i]+`">
      <div class="mb-3">
        <div class="form-check form-check-inline">
          <input class="form-check-input" type="radio" name="form-`+i+`-respuesta" id="id_form-`+i+`-respuesta" value="S">
          <label class="form-check-label" for="id_form-`+i+`-respuesta">SI</label>
        </div>
        <div class="form-check form-check-inline">
          <input class="form-check-input" type="radio" name="form-`+i+`-respuesta" id="id_form-`+i+`-respuesta" value="N">
          <label class="form-check-label" for="id_form-`+i+`-respuesta">NO</label>
        </div>
      </div>
      <label for="id_form-`+i+`-observaciones"><strong>Observaciones</strong></label>
      <textarea name="form-`+i+`-observaciones" rows="2" class="form-control" placeholder="Observaciones" style="resize: none;" id="id_form-`+i+`-observaciones"></textarea>
      
      <div id="imgfile-`+i+`-0" class="imgfile imgfile-`+i+`-p py-3 px-1">
        <input type="hidden" name="imagenrespuesta_set-`+i+`-respuesta" id="id_imagenrespuesta_set-`+i+`-respuesta">
        <p class="mb-3"><strong>Imagen(es)</strong></p>
        <input type="file" name="imagenrespuesta_set-`+i+`-imagen" class="form-control" accept="image/*" id="id_imagenrespuesta_set-`+i+`-imagen">
      </div>
    </div>
    `
    $('#inputs_resp').append(inputs)

  }

  $('#id_imagenrespuesta_set-TOTAL_FORMS').val($('.imgfile').length)
</script>
{% endblock js %}